### ISSUE TITLE
Avoid using id_to_uri?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#1189]
```
ActiveFedora::Base.reindex_everything
ActiveFedora: loading fedora config from /Users/jcoyne/workspace/sufia/.internal_test_app/config/fedora.yml
ActiveFedora: loading solr config from /Users/jcoyne/workspace/sufia/.internal_test_app/config/solr.yml
ArgumentError: Identifier must be a string of size > 0 in order to be treeified
	from /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/active_fedora-noid-2.0.1/lib/active_fedora/noid.rb:20:in `treeify'
	from /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/active_fedora-noid-2.0.1/lib/active_fedora/noid/config.rb:32:in `block in translate_id_to_uri'
	from /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/active-fedora-11.0.1/lib/active_fedora/identifiable.rb:58:in `id_to_uri'
	from /Users/jcoyne/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/active-fedora-11.0.1/lib/active_fedora/indexing.rb:86:in `reindex_everything'
```

**Comment by jcoyne** [comment]
Fixed by https://github.com/projecthydra/active_fedora/commit/3fa050a24fe34d7635d3aac2ebfbaff61dbf8a63
