### ISSUE TITLE
Unknown attribute: _attributes

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#1237]
```
work = GenericWork.create("based_near_attributes"=>{"0"=>{"id"=>"http://sws.geonames.org/5037784", "_destroy"=>"true"}}, "_attributes"=>{"1"=>{ "id"=>"http://sws.geonames.org/5809844", "_destroy"=>"true"}, "2"=>{"id"=>"http://sws.geonames.org/8965462", "_destroy"=>""}}, read_groups: ['public'], title: ["test thing"])
ActiveFedora::UnknownAttributeError: unknown attribute '_attributes' for GenericWork.
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:50:in `_assign_attribute'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:45:in `block in _assign_attributes'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:44:in `each'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:44:in `_assign_attributes'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/attribute_assignment.rb:38:in `assign_attributes'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/core.rb:37:in `initialize'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/persistence.rb:131:in `new'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/active-fedora-11.1.6/lib/active_fedora/persistence.rb:131:in `create'
```

**Comment by jcoyne** [comment]
user error
