### ISSUE TITLE
AF 5.x + Rubydora >= 1.4 test failures

### ISSUE THREAD

**Issue by cbeer** [projecthydra/active_fedora#55]
We're getting these test failures using AF 5.x and Rubydora 1.4+. Should we:

a) pin AF 5.x to Rubydora < 1.3
b) find out what to backport from `master` and try to apply it (and hope it doesn't REQUIRE Rubydora 1.4+, which I suspect it may..)
c) not care, because it seems like it's probably an edge case

```text
Failures:
  1) ActiveFedora::OmDatastream#changed? should not be changed if there are minor differences in whitespace
     Failure/Error: obj.descMetadata.should_not be_changed
       expected changed? to return false, got true
     # ./spec/integration/om_datastream_spec.rb:38:in `block (3 levels) in <top (required)>'
  2) ActiveFedora::OmDatastream.update_values should not be dirty after .update_values is saved
     Failure/Error: @test_object.datastreams["descMetadata"].should_not be_changed
       expected changed? to return false, got true
     # ./spec/integration/om_datastream_spec.rb:106:in `block (3 levels) in <top (required)>'
```

**Comment by tpendragon** [comment]
@cbeer @jcoyne We're at AF9. Can we close this as #wontfix?

**Comment by cbeer** [comment]
Sure, I think we're finally running AF 6.
