### ISSUE TITLE
Reindex_everything  raising error

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#678]
```
> ActiveFedora::Base.reindex_everything
Re-index everything ... http://127.0.0.1:8983/fedora/rest/dev/
NoMethodError: undefined method `empty?' for #<ActiveFedora::LdpResource:0x007f84b00f7170>
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/relation/finder_methods.rb:190:in `load_from_fedora'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/relation/finder_methods.rb:179:in `find_one'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/relation/finder_methods.rb:220:in `find_with_ids'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/relation/finder_methods.rb:60:in `find'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/querying.rb:3:in `find'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/indexing.rb:61:in `block in reindex_everything'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/indexing.rb:59:in `each'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.0.rc1/lib/active_fedora/indexing.rb:59:in `reindex_everything'
```

**Comment by jcoyne** [comment]
It's because descendant_uris is returning the base uri too:

```
descendent_uris(ActiveFedora::Base.id_to_uri(''))
["http://127.0.0.1:8983/fedora/rest/dev/", "http://127.0.0.1:8983/fedora/rest/dev/bernathmss315-02-01b", ...
```

**Comment by mjgiarlo** [comment]
Feh. At least we found a hole in our spec coverage! Be great to also have spec coverage of the fedora generator bug fixed earlier today.

**Comment by jcoyne** [comment]
We did have full coverage of these methods, but we didn't have an integration test.
