### ISSUE TITLE
load_instance_from_solr causes an LDP load.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#698]
```
/Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/active_fedora-e4ad57b74b80/lib/active_fedora/ldp_caching_service.rb:12:in `get'
/Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/active_fedora-e4ad57b74b80/lib/active_fedora/core.rb:180:in `build_ldp_resource'
/Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/active_fedora-e4ad57b74b80/lib/active_fedora/loadable_from_json.rb:101:in `init_with_json'
/Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/active_fedora-e4ad57b74b80/lib/active_fedora/solr_instance_loader.rb:30:in `allocate_object'
/Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/active_fedora-e4ad57b74b80/lib/active_fedora/solr_instance_loader.rb:21:in `object'
/Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/active_fedora-e4ad57b74b80/lib/active_fedora/indexing.rb:79:in `load_instance_from_solr'
```

**Comment by jcoyne** [comment]
It does get to the caching service, in never uses the initialized LdpResource object. So this seems like a non-issue.
