### ISSUE TITLE
Allow accepts_nested_attributes_for to be called earlier

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#847]
`accepts_nested_attributes_for` can not be included until all the properties are declared
 because it calls `resource_class`, which finalizes the `GeneratedResourceSchema`

This results in a very confusing error when invoking the property reader that was defined after `accepts_nested_attributes_for` was called.
```
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:157:in `predicate'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:44:in `result'
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/ActiveTriples-f925f2ae1c84/lib/active_triples/relation.rb:20:in `to_s'
     # ./spec/models/etd_spec.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by jcoyne** [comment]
At a minimum, a warning when trying to define a property after the GeneratedResourceSchema was created should raise an error.

**Comment by val99erie** [comment]
I got a different error message in a hyrax-based (1.0.x) app.  I'm just adding this comment in case someone searches for this error message, so they can more easily find this issue.

In my app, when I defined a property **after** I called `accepts_nested_attributes_for`, and then when I tried to set that property, I got this error message:

```ruby
(byebug) curation_concern.copyright_question_one = false
*** ActiveTriples::UndefinedPropertyError Exception: The property `copyright_question_one` is not defined on class 'Etd::GeneratedResourceSchema'
```
