### ISSUE TITLE
Trying to reload a belongs_to association triggers NotImplementedError

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#882]
```
class Foo < ActiveFedora::Base
  belongs_to :bar, predicate: ::RDF::URI('http://example.com/bar')
end
class Bar < ActiveFedora::Base; end
foo = Foo.new
foo.bar(true)

NotImplementedError: Need to define the uncached method
	from /Users/justin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/associations/singular_association.rb:8:in `reader'
	from /Users/justin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/associations/builder/association.rb:63:in `block in define_readers'
```

**Comment by atz** [comment]
Still true today.
