### ISSUE TITLE
Cant convert nil to string.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora#937]
```
     TypeError:
       no implicit conversion of nil into String
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:182:in `parse'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:182:in `adapt_single_attribute_value'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:165:in `adapt_attribute_value'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:143:in `block in adapt_attributes'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:142:in `each'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:142:in `each_with_object'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:142:in `adapt_attributes'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/loadable_from_json.rb:125:in `init_with_json'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/solr_instance_loader.rb:30:in `allocate_object'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/solr_instance_loader.rb:21:in `object'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/active-fedora-9.6.0/lib/active_fedora/indexing.rb:100:in `load_instance_from_solr'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-66aa92ed032e/curation_concerns-models/app/services/curation_concerns/thumbnail_path_service.rb:22:in `fetch_thumbnail'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-66aa92ed032e/curation_concerns-models/app/services/curation_concerns/thumbnail_path_service.rb:9:in `call'
     # /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-66aa92ed032e/curation_concerns-models/app/services/curation_concerns/indexes_thumbnails.rb:11:in `thumbnail_path'
     # ./app/indexers/admin_set_indexer.rb:7:in `block in generate_solr_document'
```

**Comment by jcoyne** [comment]
I yanked 9.6.0.  @ojlyytinen any ideas?
